<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="PSL-9KQ2NW2" failures="1" tests="3" name="Test - Edge" time="37.457" errors="0" timestamp="2024-02-14T15:13:13 IST">
  <testcase classname="LambdaTestKhushal.TestNGTest" name="testScenario_1" time="0.986">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [LambdaTest] but found [Selenium Grid Online | Run Selenium Test On Cloud]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [LambdaTest] but found [Selenium Grid Online | Run Selenium Test On Cloud]
at LambdaTestKhushal.TestNGTest.testScenario_1(TestNGTest.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- testScenario_1 -->
  <testcase classname="LambdaTestKhushal.TestNGTest" name="testScenario_2" time="3.945"/>
  <testcase classname="LambdaTestKhushal.TestNGTest" name="testScenario_3" time="3.54"/>
</testsuite> <!-- Test - Edge -->
